### PR TITLE
OpenImageIO v2.3

### PR DESCRIPTION
**Pull request by howetuft**
Starting from v2.3, OpenColorIO is distributed in 2 libraries. The second library (OpenColorIO_Util) needs to be added to related CMake script.

### CODE REVIEW

**Comment by howetuft** [comment]
@bartoszek
Hello,
Have you had the opportunity to review my PR? Any question? Please do not hesitate!

**Comment by bartoszek** [comment]
As I stated in AUR comment I'm currently not in a position to test/post updates, sorry. I've added you as co-maintainer, if the patch fix the current PLGBUILD script please push it to AUR and I'll merge it here afterward to preserve the coherency of the GitHub mirror.
Also would you be so kind and check if luxcorerender-git need same patch, thanks. 
I presume your AUR username is howetuft, yes?
https://aur.archlinux.org/account/howetuft

**Comment by howetuft** [comment]
Yes, you're right, my AUR username is howetuft too. I'll do it all next week-end.
By the way, I've also posted a PR for appleseed-git (same issue with OIIO v2.3), can you do the same?

**Comment by bartoszek** [comment]
Thanks, I'll take a look at Appleseed before bedtime :grin:

**Pull request merged**
